param(
    [Parameter(Mandatory = $true)][string]$InputFile,
    [Parameter(Mandatory = $true)][string]$OutputHeader,
    [string]$SymbolName = "kEmbeddedFontData"
)

$bytes = [System.IO.File]::ReadAllBytes($InputFile)
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Auto-generated by tools/embed_font.ps1 - do not edit.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <cstddef>")
[void]$sb.AppendLine("namespace neon_rush {")
[void]$sb.AppendLine("static const unsigned char $SymbolName[] = {")
for ($i = 0; $i -lt $bytes.Length; $i += 16) {
    $end = [Math]::Min($i + 16, $bytes.Length)
    $line = ($bytes[$i..($end - 1)] | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
    [void]$sb.AppendLine("  $line,")
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static constexpr std::size_t kEmbeddedFontSize = sizeof($SymbolName);")
[void]$sb.AppendLine("} // namespace neon_rush")

$dir = Split-Path -Parent $OutputHeader
if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}
[System.IO.File]::WriteAllText($OutputHeader, $sb.ToString())
Write-Host "Wrote $OutputHeader ($($bytes.Length) bytes, symbol $SymbolName)"
