# Generates NeonOps low-poly enemy/prop/weapon models as OBJ+MTL
# (per-part Kd colors, flat shading via face-normal fallback in the loader).
# All models are Y-up. Ground units author their feet at y=-1.0 because the
# game script spawns entities at y=1 (hover bob around the spawn origin);
# flying units center their body on the origin.
# Run from the repo root: python tools/gen_fps_models.py
import math
import os

OUT = "projects/fps/assets/models"


class Mesh:
    def __init__(self):
        self.verts = []
        self.faces = []  # (v1, v2, v3, material)
        self.mats = {}   # name -> (r, g, b)

    def mat(self, name, rgb):
        self.mats[name] = rgb

    def quad(self, a, b, c, d, m):
        base = len(self.verts)
        for p in (a, b, c, d):
            self.verts.append(p)
        self.faces.append((base + 1, base + 2, base + 3, m))
        self.faces.append((base + 1, base + 3, base + 4, m))

    def tri(self, a, b, c, m):
        base = len(self.verts)
        for p in (a, b, c):
            self.verts.append(p)
        self.faces.append((base + 1, base + 2, base + 3, m))

    def box(self, cx, cy, cz, sx, sy, sz, m, yaw=0.0):
        """Axis-aligned box, optionally rotated around Y (yaw, radians).
        Vertex order: for dz in (-hz,hz) for dy in (-hy,hy) for dx in (-hx,hx).
        Quads are proper loops (no bowties) with outward-facing winding."""
        hx, hy, hz = sx / 2, sy / 2, sz / 2
        pts = []
        for dz in (-hz, hz):
            for dy in (-hy, hy):
                for dx in (-hx, hx):
                    x, z = dx, dz
                    if yaw:
                        x = dx * math.cos(yaw) + dz * math.sin(yaw)
                        z = -dx * math.sin(yaw) + dz * math.cos(yaw)
                    pts.append((cx + x, cy + dy, cz + z))
        # 0:(-x,-y,-z) 1:(+x,-y,-z) 2:(-x,+y,-z) 3:(+x,+y,-z)
        # 4:(-x,-y,+z) 5:(+x,-y,+z) 6:(-x,+y,+z) 7:(+x,+y,+z)
        self.quad(pts[4], pts[5], pts[7], pts[6], m)  # +z front
        self.quad(pts[1], pts[0], pts[2], pts[3], m)  # -z back
        self.quad(pts[5], pts[1], pts[3], pts[7], m)  # +x right
        self.quad(pts[0], pts[4], pts[6], pts[2], m)  # -x left
        self.quad(pts[6], pts[7], pts[3], pts[2], m)  # +y top
        self.quad(pts[0], pts[1], pts[5], pts[4], m)  # -y bottom

    def cyl(self, cx, cy, cz, r_top, r_bot, h, seg, m, cap=True):
        for i in range(seg):
            a0 = 2 * math.pi * i / seg
            a1 = 2 * math.pi * (i + 1) / seg
            x0t, z0t = cx + r_top * math.cos(a0), cz + r_top * math.sin(a0)
            x1t, z1t = cx + r_top * math.cos(a1), cz + r_top * math.sin(a1)
            x0b, z0b = cx + r_bot * math.cos(a0), cz + r_bot * math.sin(a0)
            x1b, z1b = cx + r_bot * math.cos(a1), cz + r_bot * math.sin(a1)
            y0, y1 = cy - h / 2, cy + h / 2
            self.quad((x0b, y0, z0b), (x1b, y0, z1b), (x1t, y1, z1t), (x0t, y1, z0t), m)
            if cap:
                self.tri((cx, y1, cz), (x0t, y1, z0t), (x1t, y1, z1t), m)
                if r_bot > 0:
                    self.tri((cx, y0, cz), (x1b, y0, z1b), (x0b, y0, z0b), m)

    def octa(self, cx, cy, cz, r, m):
        p = [(cx, cy + r, cz), (cx, cy - r, cz),
             (cx - r, cy, cz), (cx + r, cy, cz), (cx, cy, cz - r), (cx, cy, cz + r)]
        for top in (0, 1):
            ring = (2, 4, 3, 5) if top == 0 else (5, 3, 4, 2)
            for k in range(4):
                self.tri(p[top], p[ring[k]], p[ring[(k + 1) % 4]], m)

    def sphere(self, cx, cy, cz, r, seg_u, seg_v, m):
        rows = []
        for j in range(seg_v + 1):
            phi = math.pi * j / seg_v
            row = []
            for i in range(seg_u):
                th = 2 * math.pi * i / seg_u
                row.append((cx + r * math.sin(phi) * math.cos(th),
                            cy + r * math.cos(phi),
                            cz + r * math.sin(phi) * math.sin(th)))
            rows.append(row)
        for j in range(seg_v):
            for i in range(seg_u):
                j2 = i + 1 if i + 1 < seg_u else 0
                if j == 0:
                    self.tri(rows[0][0], rows[1][j2], rows[1][i], m)
                elif j == seg_v - 1:
                    self.tri(rows[j + 1][0], rows[j][i], rows[j][j2], m)
                else:
                    self.quad(rows[j][i], rows[j][j2], rows[j + 1][j2], rows[j + 1][i], m)

    def write(self, name, mtl=True):
        obj = os.path.join(OUT, name + ".obj")
        with open(obj, "w") as f:
            f.write("# %s.obj - generated by tools/gen_fps_models.py (y-up)\n" % name)
            if mtl:
                f.write("mtllib %s.mtl\n" % name)
            for v in self.verts:
                f.write("v %.4f %.4f %.4f\n" % v)
            if mtl:
                cur = None
                for a, b, c, m in self.faces:
                    if m != cur:
                        f.write("usemtl %s\n" % m)
                        cur = m
                    f.write("f %d %d %d\n" % (a, b, c))
        if mtl:
            with open(os.path.join(OUT, name + ".mtl"), "w") as f:
                f.write("# %s.mtl - generated\n" % name)
                for name_m, (r, g, b) in self.mats.items():
                    f.write("newmtl %s\nKd %.3f %.3f %.3f\nKa 0 0 0\nKs 0 0 0\n"
                            "illum 1\n\n" % (name_m, r, g, b))
        n = len(self.verts)
        print("  %-22s %4d verts %4d tris" % (name + ".obj", n, len(self.faces) * 2))


# --- palette -------------------------------------------------------------
STEEL = (0.32, 0.36, 0.42)
GUNMETAL = (0.22, 0.24, 0.28)
DARK = (0.13, 0.14, 0.17)
RED = (0.90, 0.18, 0.14)
ORANGE = (0.95, 0.55, 0.10)
AMBER = (0.98, 0.72, 0.15)
CYAN = (0.25, 0.85, 0.95)
CRIMSON = (0.75, 0.12, 0.22)
WHITE = (0.88, 0.90, 0.92)
OLIVE = (0.42, 0.46, 0.30)
BRASS = (0.80, 0.62, 0.25)
CONCRETE = (0.58, 0.60, 0.62)
YELLOW = (0.92, 0.78, 0.20)
PURPLE = (0.62, 0.25, 0.85)

# HDR emissive materials: components above 1.0 glow through the lit shader's
# tint self-glow path (tint - 1.0 emits, modulated by albedo) and bloom.
GLOW_RED = (1.0, 0.10, 0.08)        # tint 1.0 -> +0.0 red? no: tint stays, glow = tint-1
GLOW_RED = (1.6, 0.22, 0.12)        # red lamp
GLOW_CYAN = (0.30, 1.7, 1.9)        # cyan lamp
GLOW_AMBER = (1.9, 1.35, 0.25)      # amber lamp
GLOW_PURPLE = (1.45, 0.35, 1.9)     # violet lamp
GLOW_GREEN = (0.35, 1.8, 0.55)      # health glow


def gen_drone():
    m = Mesh()
    m.mat("body", STEEL); m.mat("dark", DARK); m.mat("eye", GLOW_RED)
    m.mat("rotor", GUNMETAL); m.mat("trim", CYAN)
    m.octa(0, 0, 0, 0.26, "body")                       # core
    m.box(0, -0.10, 0, 0.20, 0.14, 0.20, "dark")        # belly pod
    # 4 rotor arms in X shape
    for ax, az in ((1, 1), (1, -1), (-1, 1), (-1, -1)):
        cx, cz = ax * 0.30, az * 0.30
        m.box(cx * 0.5, 0.02, cz * 0.5, 0.34, 0.05, 0.07, "dark",
              yaw=math.atan2(az, ax))
        m.cyl(cx, 0.06, cz, 0.16, 0.16, 0.03, 10, "rotor")   # rotor disc
        m.cyl(cx, 0.10, cz, 0.03, 0.03, 0.10, 6, "dark")     # hub
    m.box(0, 0.02, 0.24, 0.14, 0.10, 0.06, "eye")       # front eye (faces +z)
    m.box(0, 0.14, -0.16, 0.10, 0.04, 0.14, "trim")     # nav stripe
    m.write("enemy_drone")


def gen_turret():
    m = Mesh()
    m.mat("base", DARK); m.mat("steel", STEEL); m.mat("dome", GUNMETAL)
    m.mat("barrel", DARK); m.mat("acc", GLOW_RED); m.mat("ring", CYAN)
    # feet at y=-1.0 (entity spawns at y=1)
    m.cyl(0, -0.94, 0, 0.42, 0.50, 0.12, 8, "base")     # ground pad
    m.cyl(0, -0.78, 0, 0.26, 0.36, 0.28, 8, "steel")    # pedestal
    m.cyl(0, -0.52, 0, 0.34, 0.30, 0.10, 8, "ring")     # yaw ring accent
    m.sphere(0, -0.36, 0, 0.30, 10, 6, "dome")          # armored dome
    m.box(0, -0.36, 0.26, 0.16, 0.12, 0.10, "acc")      # sensor
    m.box(0.09, -0.30, 0.38, 0.07, 0.07, 0.34, "barrel")  # twin barrels (+z fwd)
    m.box(-0.09, -0.30, 0.38, 0.07, 0.07, 0.34, "barrel")
    m.box(0.09, -0.30, 0.56, 0.09, 0.09, 0.06, "acc")
    m.box(-0.09, -0.30, 0.56, 0.09, 0.09, 0.06, "acc")
    m.box(0.24, -0.44, 0, 0.10, 0.16, 0.22, "steel")    # shoulder armor
    m.box(-0.24, -0.44, 0, 0.10, 0.16, 0.22, "steel")
    m.write("enemy_turret")


def gen_sapper():
    m = Mesh()
    m.mat("shell", ORANGE); m.mat("band", DARK); m.mat("core", GLOW_AMBER)
    m.mat("fin", DARK)
    m.sphere(0, 0, 0, 0.26, 10, 6, "shell")
    m.cyl(0, 0.0, 0, 0.27, 0.27, 0.07, 10, "band")      # hazard band
    m.sphere(0, 0, 0.20, 0.09, 6, 4, "core")            # trigger core
    for a in (0, 2.09, 4.19):                            # 3 tail fins
        fx, fz = 0.28 * math.cos(a), 0.28 * math.sin(a)
        m.box(fx * 1.3, -0.05, fz * 1.3, 0.20, 0.03, 0.10, "fin",
              yaw=-a)
    m.cyl(0, -0.30, 0, 0.04, 0.04, 0.10, 6, "fin")      # ventral spike
    m.write("enemy_sapper")


def gen_heavy():
    m = Mesh()
    m.mat("armor", STEEL); m.mat("dark", DARK); m.mat("visor", GLOW_RED)
    m.mat("gun", GUNMETAL); m.mat("trim", GLOW_AMBER)
    # legs (feet at y=-1.0)
    for sx in (-1, 1):
        m.box(sx * 0.20, -0.72, 0, 0.22, 0.60, 0.26, "dark")
        m.box(sx * 0.20, -0.98, 0.04, 0.26, 0.12, 0.40, "armor")
        m.box(sx * 0.20, -0.42, 0, 0.26, 0.14, 0.30, "armor")  # knee guard
    # torso
    m.box(0, 0.02, 0, 0.66, 0.56, 0.42, "armor")
    m.box(0, 0.02, 0.20, 0.40, 0.30, 0.06, "dark")       # chest plate
    m.box(0, 0.16, 0.235, 0.26, 0.08, 0.03, "visor")     # chest sensor
    m.box(0, -0.16, 0.22, 0.30, 0.10, 0.04, "trim")      # belt light
    # head
    m.box(0, 0.40, 0.02, 0.30, 0.22, 0.30, "dark")
    m.box(0, 0.40, 0.16, 0.22, 0.10, 0.04, "visor")
    # shoulders + arm cannons
    for sx in (-1, 1):
        m.box(sx * 0.44, 0.16, 0, 0.24, 0.26, 0.34, "armor")
        m.box(sx * 0.44, -0.12, 0.10, 0.16, 0.34, 0.18, "gun")
        m.box(sx * 0.44, -0.30, 0.24, 0.10, 0.10, 0.10, "trim")
    m.write("enemy_heavy")


def gen_boss():
    m = Mesh()
    m.mat("armor", GUNMETAL); m.mat("dark", DARK); m.mat("visor", GLOW_PURPLE)
    m.mat("gun", STEEL); m.mat("acc", GLOW_PURPLE)
    # thick legs
    for sx in (-1, 1):
        m.box(sx * 0.34, -0.70, 0, 0.34, 0.56, 0.40, "dark")
        m.box(sx * 0.34, -0.97, 0.05, 0.40, 0.14, 0.58, "armor")
        m.box(sx * 0.34, -0.40, 0, 0.38, 0.16, 0.44, "armor")
    # massive torso
    m.box(0, 0.06, 0, 1.00, 0.66, 0.58, "armor")
    m.box(0, 0.06, 0.28, 0.56, 0.40, 0.08, "dark")
    m.box(0, 0.22, 0.325, 0.36, 0.10, 0.03, "visor")
    m.box(0, -0.14, 0.30, 0.44, 0.12, 0.05, "acc")
    # head
    m.box(0, 0.52, 0.02, 0.36, 0.26, 0.36, "dark")
    m.box(0, 0.52, 0.19, 0.26, 0.12, 0.04, "visor")
    # shoulders + heavy cannons
    for sx in (-1, 1):
        m.box(sx * 0.66, 0.22, 0, 0.32, 0.34, 0.44, "armor")
        m.box(sx * 0.66, -0.10, 0.14, 0.20, 0.42, 0.22, "gun")
        m.box(sx * 0.66, -0.32, 0.32, 0.13, 0.13, 0.14, "acc")
    # back thrusters
    for sx in (-1, 1):
        m.cyl(sx * 0.26, 0.10, -0.36, 0.09, 0.11, 0.30, 8, "dark")
    m.box(0, 0.44, -0.30, 0.70, 0.10, 0.10, "acc")       # top antenna bar
    m.write("enemy_boss")


def gen_barrier():
    m = Mesh()
    m.mat("concrete", CONCRETE); m.mat("stripe", YELLOW); m.mat("foot", DARK)
    # jersey barrier, feet at y=-1.0, 2.0 long (x), 0.45 deep, 1.0 tall
    m.box(0, -0.90, 0, 2.0, 0.24, 0.44, "concrete")      # base block
    m.box(0, -0.55, 0, 2.0, 0.50, 0.30, "concrete")      # mid
    m.box(0, -0.30, 0, 1.9, 0.10, 0.32, "stripe")        # hazard stripe
    m.box(0, -0.10, 0, 2.0, 0.34, 0.22, "concrete")      # top
    for sx in (-0.85, 0.85):
        m.box(sx, -0.98, 0, 0.20, 0.10, 0.52, "foot")    # feet
    m.write("cover_barrier")


def gen_pickups():
    m = Mesh()
    m.mat("case", WHITE); m.mat("cross", GLOW_GREEN); m.mat("edge", DARK)
    m.box(0, 0, 0, 0.34, 0.34, 0.22, "case")
    m.box(0, 0, 0.115, 0.20, 0.07, 0.02, "cross")
    m.box(0, 0, 0.115, 0.07, 0.20, 0.02, "cross")
    m.box(0, 0.185, 0, 0.36, 0.03, 0.24, "edge")
    m.box(0, -0.185, 0, 0.36, 0.03, 0.24, "edge")
    m.write("pickup_health")

    m = Mesh()
    m.mat("can", OLIVE); m.mat("lid", DARK); m.mat("tip", GLOW_AMBER)
    m.box(0, 0, 0, 0.38, 0.24, 0.24, "can")
    m.box(0, 0.135, 0, 0.40, 0.04, 0.26, "lid")
    for i in range(4):
        m.cyl(-0.12 + i * 0.08, 0.19, 0, 0.025, 0.025, 0.05, 6, "tip")
    m.write("pickup_ammo")


def gen_weapons():
    """First-person viewmodels. muzzle points -Z, grip near origin.
    Multi-part materials: body/grip/mag/accents."""
    def rifle():
        m = Mesh()
        m.mat("body", GUNMETAL); m.mat("dark", DARK); m.mat("grip", (0.16, 0.13, 0.10))
        m.mat("mag", STEEL); m.mat("acc", CYAN); m.mat("sight", GLOW_RED)
        m.box(0, 0, -0.20, 0.075, 0.09, 0.55, "body")        # receiver
        m.box(0, 0.005, -0.60, 0.045, 0.045, 0.30, "dark")   # handguard
        m.cyl(0, 0.005, -0.83, 0.016, 0.016, 0.14, 8, "dark")  # barrel
        m.box(0, 0.075, -0.14, 0.03, 0.05, 0.16, "acc")      # top rail accent
        m.box(0, 0.11, -0.05, 0.035, 0.05, 0.05, "sight")    # red-dot
        m.box(0, -0.13, 0.02, 0.06, 0.16, 0.09, "grip", yaw=0.18)
        m.box(0, -0.12, -0.24, 0.05, 0.20, 0.10, "mag", yaw=-0.10)
        m.box(0, 0.01, 0.16, 0.06, 0.11, 0.18, "body")       # stock
        m.box(0, 0.06, 0.24, 0.05, 0.09, 0.05, "dark")       # stock pad
        return m

    def shotgun():
        m = Mesh()
        m.mat("body", (0.45, 0.30, 0.16)); m.mat("dark", DARK); m.mat("grip", (0.16, 0.13, 0.10))
        m.mat("pump", STEEL); m.mat("acc", AMBER)
        m.box(0, 0, -0.16, 0.07, 0.10, 0.42, "body")
        m.cyl(0, 0.02, -0.55, 0.030, 0.030, 0.50, 8, "dark")   # barrel
        m.cyl(0, -0.045, -0.55, 0.024, 0.024, 0.44, 8, "dark")  # tube
        m.box(0, -0.045, -0.52, 0.07, 0.06, 0.16, "pump")       # pump
        m.box(0, 0.075, -0.10, 0.035, 0.04, 0.20, "acc")        # rail
        m.box(0, -0.13, 0.04, 0.06, 0.16, 0.09, "grip", yaw=0.22)
        m.box(0, -0.02, 0.18, 0.065, 0.13, 0.20, "body")        # stock
        return m

    def sniper():
        m = Mesh()
        m.mat("body", (0.30, 0.34, 0.30)); m.mat("dark", DARK); m.mat("grip", (0.16, 0.13, 0.10))
        m.mat("scope", DARK); m.mat("lens", GLOW_CYAN); m.mat("mag", STEEL)
        m.box(0, 0, -0.18, 0.07, 0.09, 0.62, "body")
        m.cyl(0, 0.01, -0.85, 0.017, 0.017, 0.44, 8, "dark")    # long barrel
        m.box(0, 0.005, -1.02, 0.05, 0.05, 0.10, "dark")        # muzzle brake
        m.cyl(0, 0.115, -0.20, 0.045, 0.045, 0.34, 10, "scope")  # scope tube
        m.cyl(0, 0.115, -0.40, 0.055, 0.045, 0.03, 10, "lens")
        m.box(0, 0.06, -0.20, 0.03, 0.05, 0.06, "dark")         # mount
        m.box(0, -0.13, 0.03, 0.06, 0.16, 0.09, "grip", yaw=0.20)
        m.box(0, -0.12, -0.22, 0.05, 0.16, 0.11, "mag")
        m.box(0, -0.01, 0.20, 0.06, 0.12, 0.24, "body")         # stock
        m.box(0, -0.09, 0.30, 0.07, 0.08, 0.06, "dark")         # cheek pad
        return m

    def smg():
        m = Mesh()
        m.mat("body", (0.36, 0.38, 0.44)); m.mat("dark", DARK); m.mat("grip", (0.16, 0.13, 0.10))
        m.mat("mag", STEEL); m.mat("acc", RED)
        m.box(0, 0, -0.14, 0.07, 0.10, 0.36, "body")            # compact receiver
        m.cyl(0, 0.01, -0.42, 0.018, 0.018, 0.18, 8, "dark")    # short barrel
        m.box(0, 0.075, -0.08, 0.03, 0.04, 0.14, "acc")         # rail
        m.box(0, -0.15, -0.06, 0.05, 0.24, 0.08, "mag")         # long mag
        m.box(0, -0.13, 0.06, 0.06, 0.15, 0.08, "grip", yaw=0.15)
        m.box(0, 0.01, 0.14, 0.05, 0.10, 0.12, "dark")          # stock brace
        return m

    for name, fn in (("weapon_rifle_fp", rifle), ("weapon_shotgun_fp", shotgun),
                     ("weapon_sniper_fp", sniper), ("weapon_smg_fp", smg)):
        fn().write(name)


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    print("generating models into", OUT)
    gen_drone()
    gen_turret()
    gen_sapper()
    gen_heavy()
    gen_boss()
    gen_barrier()
    gen_pickups()
    gen_weapons()
