param(
    [Parameter(Mandatory = $true)][string]$Glslang,
    [Parameter(Mandatory = $true)][string]$ShaderDir,
    [Parameter(Mandatory = $true)][string]$SpvDir,
    [Parameter(Mandatory = $true)][string]$OutputHeader
)

# Build-time Vulkan shader generator (T7.1).
#
# Compiles the engine's built-in Vulkan GLSL shaders to SPIR-V with a vendored
# glslang and embeds the result as uint32 word arrays in
# engine/generated/vk_shaders.hpp, so the runtime needs no external shader
# files (matching the project's zero-runtime-assets ethos). The header is
# committed; this script only re-runs when a shader source changes and the
# tool is present.

# name;vertex_file;fragment_file[;MACRO=1[,MACRO2=1]]
$shaders = @(
    "lit;lit.vert;lit.frag",
    "lit_skinned;lit_skinned.vert;lit.frag",
    "unlit;unlit.vert;unlit.frag",
    "ui;ui.vert;ui.frag",
    "lines;lines.vert;lines.frag",
    "lit_instanced;lit_instanced.vert;lit.frag",
    "unlit_instanced;unlit_instanced.vert;unlit.frag",
    "unlit_instanced_colored;unlit_instanced_colored.vert;unlit_instanced_colored.frag",
    "shadow;shadow.vert;shadow.frag",
    "shadow_inst;shadow_instanced.vert;shadow.frag",
    "shadow_skin;shadow_skinned.vert;shadow.frag",
    "point_shadow;point_shadow.vert;point_shadow.frag",
    "point_shadow_inst;point_shadow_instanced.vert;point_shadow.frag",
    "point_shadow_skin;point_shadow_skinned.vert;point_shadow.frag",
    "bloom_bright;post.vert;bright.frag",
    "bloom_blur;post.vert;blur.frag",
    "bloom_downsample;post.vert;downsample.frag",
    "bloom_upsample_add;post.vert;upsample_add.frag",
    "bloom_composite;post.vert;composite.frag",
    # G1-5 depth / AO / SSR / volumetric post chain.
    "ssao_depth;ssao_depth.vert;ssao_depth.frag",
    "ssao_depth_mesh;ssao_depth_mesh.vert;ssao_depth.frag",
    "ssao_depth_skinned;ssao_depth_skinned.vert;ssao_depth.frag",
    "depth_encode;post.vert;depth_encode.frag",
    "ssao;post.vert;ssao.frag",
    "ssao_blur;post.vert;ssao_blur.frag",
    "volumetric;post.vert;volumetric.frag",
    "ssr;post.vert;ssr.frag",
"ssr_blur;post.vert;ssr_blur.frag",
    # A5 auto-exposure chain.
    "autoexposure_lum;post.vert;autoexposure_lum.frag",
    "autoexposure_avg;post.vert;autoexposure_avg.frag",
    "autoexposure_adapt;post.vert;autoexposure_adapt.frag",
    # Procedural sky + MOBA effect programs.
    "skybox;skybox.vert;skybox.frag",
    "particle;particle.vert;unlit_instanced_colored.frag",
    "particle_soft;particle_soft.vert;particle_soft.frag",
    "decal;decal.vert;decal.frag",
    "lit_terrain;lit.vert;lit.frag;TERRAIN_SPLAT=1",
    # Step E/E2: temporal AA (resolve + sharpen), motion vectors, and the
    # backend-internal MSAA depth resolve the resolve pass reprojects from.
    "velocity;velocity.vert;velocity.frag",
    "taa;post.vert;taa.frag",
    "taa_sharpen;post.vert;taa_sharpen.frag",
    "depth_resolve;post.vert;depth_resolve.frag"
)

if (-not (Test-Path $Glslang)) {
    Write-Error "glslang not found at '$Glslang'"
    exit 1
}
New-Item -ItemType Directory -Force -Path $SpvDir | Out-Null

function Get-SpvWords([string]$SpvPath) {
    $bytes = [System.IO.File]::ReadAllBytes($SpvPath)
    $words = New-Object 'System.Collections.Generic.List[uint32]'
    for ($i = 0; $i + 3 -lt $bytes.Length; $i += 4) {
        $words.Add([System.BitConverter]::ToUInt32($bytes, $i))
    }
    return $words
}

function Write-WordArray([System.Text.StringBuilder]$Sb, [string]$ArrayName,
                         [System.Collections.Generic.List[uint32]]$Words) {
    [void]$Sb.AppendLine("static const uint32_t ${ArrayName}[] = {")
    for ($i = 0; $i -lt $Words.Count; $i += 8) {
        $end = [Math]::Min($i + 8, $Words.Count)
        $parts = @()
        for ($k = $i; $k -lt $end; $k++) {
            $parts += ("0x{0:X8}u" -f $Words[$k])
        }
        [void]$Sb.AppendLine("    " + ($parts -join ", ") + ",")
    }
    [void]$Sb.AppendLine("};")
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Auto-generated by tools/gen_vk_shaders.ps1 - do not edit.")
[void]$sb.AppendLine("// Built-in Vulkan shaders precompiled to SPIR-V with the vendored")
[void]$sb.AppendLine("// glslang (third_party/glslang_tool). Lookup keyed by shader debugName.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <cstdint>")
[void]$sb.AppendLine("namespace neon { namespace gfx { namespace vk {")
[void]$sb.AppendLine("struct VkShaderSpv {")
[void]$sb.AppendLine("    const char* name;")
[void]$sb.AppendLine("    const uint32_t* vert; uint32_t vertWords;")
[void]$sb.AppendLine("    const uint32_t* frag; uint32_t fragWords;")
[void]$sb.AppendLine("};")

$names = @()
foreach ($entry in $shaders) {
    $parts = $entry -split ";"
    $name = $parts[0]
    $vertFile = $parts[1]
    $fragFile = $parts[2]
    # Optional 4th field: comma-separated preprocessor defines for glslang.
    $defArgs = @()
    if ($parts.Count -ge 4 -and $parts[3]) {
        foreach ($d in ($parts[3] -split ",")) { $defArgs += @("-D$d") }
    }
    $names += $name

    $vertSpv = Join-Path $SpvDir "$name.vert.spv"
    $fragSpv = Join-Path $SpvDir "$name.frag.spv"
    & $Glslang -V "-I$ShaderDir" @defArgs -o $vertSpv (Join-Path $ShaderDir $vertFile) 2>$null
    if ($LASTEXITCODE -ne 0) { Write-Error "glslang failed on $vertFile"; exit 1 }
    & $Glslang -V "-I$ShaderDir" @defArgs -o $fragSpv (Join-Path $ShaderDir $fragFile) 2>$null
    if ($LASTEXITCODE -ne 0) { Write-Error "glslang failed on $fragFile"; exit 1 }

    Write-WordArray $sb "k${name}Vert" (Get-SpvWords $vertSpv)
    Write-WordArray $sb "k${name}Frag" (Get-SpvWords $fragSpv)
}

[void]$sb.AppendLine("const VkShaderSpv kShaderTable[] = {")
foreach ($name in $names) {
    [void]$sb.AppendLine("    {`"${name}`", k${name}Vert, sizeof(k${name}Vert) / 4, k${name}Frag, sizeof(k${name}Frag) / 4},")
}
[void]$sb.AppendLine("    {`"imgui`", kuiVert, sizeof(kuiVert) / 4, kuiFrag, sizeof(kuiFrag) / 4},")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("} } } // namespace neon::gfx::vk")

$dir = Split-Path -Parent $OutputHeader
if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}
[System.IO.File]::WriteAllText($OutputHeader, $sb.ToString())
Write-Host "Wrote $OutputHeader ($($shaders.Count) shader programs)"
